# name: Test & Deploy

# on:
#   push:
#     branches: [ Deployment ]  

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest  

#     steps:
#       - uses: actions/checkout@v4  

#       # **Angular app unit tests**
#       - name: Set up Node.js environment
#         uses: actions/setup-node@v2
#         with:
#           node-version: '21' 

#       - name: Install Angular dependencies (if using npm)
#         run: |
#           cd Client
#           npm install
#       - name: Run Angular unit tests on Client App
#         run: |
#           cd Client
#           npm test -- --watch=false --browsers=ChromeHeadless

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v4
#         with:
#             dotnet-version: 8.0.x
#       - name: Restore dependencies
#         run: |
#             cd WebApi
#             dotnet restore
#       - name: Build .NET APP
#         run: | 
#             cd WebApi
#             dotnet build --no-restore
#       - name: Run Unit Test on .NET APP
#         run: | 
#             cd WebApi
#             dotnet test --no-build --verbosity normal

#       - name: Build Client App
#         run: |
#           cd Client
#           npm run build
      
#       - name: Release .NET for Publish
#         run: |
#             cd WebApi
#             mkdir publish
#             dotnet publish -c Release -o ./publish

#       - name: Backup files Before Deploy
#         uses: appleboy/ssh-action@master
#         with:
#             host: ${{ secrets.HOST }}
#             username: ${{ secrets.USERNAME }}
#             port: ${{ secrets.PORT }}
#             password: ${{ secrets.PASSWORD }}
           
      
#       - name: Deploy ClientApp VPS
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           password: ${{ secrets.PASSWORD }}
#           strip_components: 4

#       - name: Deploy WebAPI to VPS
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           port: ${{ secrets.PORT }}
#           password: ${{ secrets.PASSWORD }}
#           target: ${{ secrets.WEBAPI_APP_PATH }}
#           strip_components: 4

#       - name: Restart Server
#         uses: appleboy/ssh-action@master
#         with:
#             host: ${{ secrets.HOST }}
#             username: ${{ secrets.USERNAME }}
#             port: ${{ secrets.PORT }}
#             password: ${{ secrets.PASSWORD }}
           
